# Generated by Django 4.2.1 on 2023-06-01 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0004_customgroup_custompermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
        migrations.DeleteModel(
            name='CustomPermission',
        ),
    ]
