# Generated by Django 4.2.1 on 2023-06-02 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0005_delete_customgroup_delete_custompermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
